### ISSUE TITLE
iFoundADog BAT set-up

### ISSUE THREAD

**Issue by jhibbets** [codeforamerica/bat-iFoundADog#2]
A few requests for you:

- [x] Can you create the following Google Group:
bat-iFoundADog@codeforamerica.org, visibility set to public

- [x]  Add the following people as Group admins:
christopher.m.hedrick@gmail.com
jeff.elkner@gmail.com
elauridsen03@gmail.com
jhibbets@gmail.com

- [x]  Add the following GitHub accounts to the CfA organization:
cmhedrick <-- already done!
jelkner

**Comment by tdooner** [comment]
@cmhedrick @jelkner Welcome! Let me know if anything looks amiss.
